# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# URL: projecteuler.net/problem=2
# Username: Arjun.Kiran

# Work Thoughts
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
# 0, E, 0, 0, E,  0,  0,  E,  0,  0,
# t1,t2,t3,t4,t5, t6,t7,  t8, t9, t10


import math


def fib(n):
	"""This is a basic Fibonacci function but does not scale"""
	if n == 1:
		breturn = 1
	elif n == 2:
		breturn = 2
	else:
		# using recursion
		breturn = fib(n-1) + fib(n-2)

	return breturn


class fibObject:
	"""A faster version of the fib function"""
	def __init__(self):
		# intializing the first three terms
		# self.terms array is used as memory 
		# and stored perviously found fibonacci numbers 
		# to prevent duplication of work
		self.terms = [0,1,2]

	def fib(self,n):
		if len(self.terms) > n:
			# n is less than number of store fibonacci number
			# that means that term is already found
			breturn = self.terms[n]
		else:
			# newly discovered fibonacci number
			# stored after calculated
			breturn = self.fib(n-1) + self.fib(n-2)
			self.terms.append(breturn)

		return breturn

def main():
	obj = fibObject()
	# starts at 2 because fibanacci numbers 1,2 are already determined
	term_Number = 2
	term_Value = obj.fib(term_Number) 
	sum = 0
	while(term_Value < 4000000):
		sum = sum + term_Value
		term_Number = term_Number + 3
		term_Value = obj.fib(term_Number)

	print sum

if __name__ == '__main__':
	main()

